- hosts:
  - boerhaave-exhibits-all
  roles:
      #- angstwad.docker_ubuntu
    - {
      role: "softasap.sa-vnc-remote-desktop",
      vnc_password: "mansveld"
      }
    - wtanaka.teamviewer
    #- atzedevries.boerhaave-exhibit
